name: Nightly Build

on:
  schedule:
   - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Tag
      run: |
        git fetch --tags origin
        git tag -f next_macOS
        git push -f origin next_macOS
    - name: Build
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j6
    - name: Test
      run: make test
    - name: Package
      run: python3 tools/pack.py
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: macOS nightly build
        tag_name: next_macOS
        prerelease: true
        draft: false
        files: |
          nasal-macOS-aarch64.tar
    
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Tag
      run: |
        git fetch --tags origin
        git tag -f next_linux_x86_64
        git push -f origin next_linux_x86_64
    - name: Build
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j6
    - name: Test
      run: make test
    - name: Package
      run: python3 tools/pack.py
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: linux nightly build
        tag_name: next_linux_x86_64
        prerelease: true
        draft: false
        files: |
          nasal-linux-x86_64.tar
