name: Build/Test/Package CI

on:
  schedule:
   - cron: "0 16 * * *"
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          make -j4
          cd module
          make all -j4
          cd ..
    - name: Test
      run: make test
    - name: Package
      run: python3 tools/pack.py
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: macOS nightly build
        tag_name: next_macOS
        prerelease: true
        files: |
          nasal-Darwin.tar
    
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          make -j4
          cd module
          make all -j4
          cd ..
    - name: Test
      run: make test
    - name: Package
      run: python3 tools/pack.py
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: linux nightly build
        tag_name: next_linux_x86_64
        prerelease: true
        files: |
          nasal-Linux.tar
