name: Nasal Interpreter Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  mac-aarch64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j6
    - name: Test
      run: make test
    
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j6
    - name: Test
      run: make test
